[package]
name = "bplus"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
path_macro = "1.0.0"
serde = { version = "1.0.195", features = ["derive"] }
thiserror = "1.0.56"
uuid = { version = "1.6.1", features = ["v4", "serde"] }
